ProfesionalesMVC/Controllers/ActividadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProfesionalesMVC.Models;

namespace ProfesionalesMVC.Controllers
{
    public class ActividadesController : Controller
    {
        private readonly Context _context;

        public ActividadesController(Context context)
        {
            _context = context;
        }

        // GET: Actividades
        public async Task<IActionResult> Index()
        {
              return _context.Actividades != null ? 
                          View(await _context.Actividades.ToListAsync()) :
                          Problem("Entity set 'Context.Actividades'  is null.");
        }

        // GET: Actividades/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Actividades == null)
            {
                return NotFound();
            }

            var actividad = await _context.Actividades
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actividad == null)
            {
                return NotFound();
            }

            return View(actividad);
        }

        // GET: Actividades/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actividades/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre")] Actividad actividad)
        {
            if (ModelState.IsValid)
            {
                _context.Add(actividad);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actividad);
        }

        // GET: Actividades/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Actividades == null)
            {
                return NotFound();
            }

            var actividad = await _context.Actividades.FindAsync(id);
            if (actividad == null)
            {
                return NotFound();
            }
            return View(actividad);
        }

        // POST: Actividades/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre")] Actividad actividad)
        {
            if (id != actividad.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(actividad);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActividadExists(actividad.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actividad);
        }

        // GET: Actividades/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Actividades == null)
            {
                return NotFound();
            }

            var actividad = await _context.Actividades
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actividad == null)
            {
                return NotFound();
            }

            return View(actividad);
        }

        // POST: Actividades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Actividades == null)
            {
                return Problem("Entity set 'Context.Actividades'  is null.");
            }
            var actividad = await _context.Actividades.FindAsync(id);
            if (actividad != null)
            {
                _context.Actividades.Remove(actividad);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActividadExists(int id)
        {
          return (_context.Actividades?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ProfesionalesMVC/Controllers/ProfesionalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProfesionalesMVC.Models;

namespace ProfesionalesMVC.Controllers
{
    public class ProfesionalesController : Controller
    {
        private readonly Context _context;

        public ProfesionalesController(Context context)
        {
            _context = context;
        }

        // GET: Profesionales
        public async Task<IActionResult> Index(string? search, string? field)
        {
            
            search = search?.Trim();
            field = field?.Trim();

            search = search == "" ? null : search;
            field = field == "" || field == "Todos" ? null : field;

            ViewData ["Fields"] = new SelectList(typeof(Profesional).GetProperties().Where(x => x.PropertyType != typeof(bool) && !typeof(IEnumerable<Object>).IsAssignableFrom(x.PropertyType)).Select(x => x.Name).Append("Todos"), field ?? "Todos");

            return _context.Profesionales != null ? 
                          View(search == null ? await _context.Profesionales.ToListAsync() : 
                            (
                            field == null ?
                                await _context.Profesionales.Where(x => x.Nombre.Contains(search)).ToListAsync()
                                : await _context.SearchBy<Profesional>(field, search, _context.Profesionales)
                            ))
                          : Problem("Entity set 'Context.Profesionales'  is null.");
        }

        // GET: Profesionales/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null || _context.Profesionales == null)
            {
                return NotFound();
            }

            IEnumerable<ProfesionalActividad?> actividadesDone = _context.Profesionales.Include(x => x.ProfesionalesActividades).ThenInclude(x => x.Actividad).First(x => x.Id == id).ProfesionalesActividades;
            ViewData ["ActivitiesDone"] = actividadesDone;

            var actividades = await _context.Actividades.ToListAsync();

            ViewData ["Activities"] = new SelectList(actividades.Except(actividadesDone.Select(x => x.Actividad)), "Id", "Nombre");

            var profesional = await _context.Profesionales
                .FirstOrDefaultAsync(m => m.Id == id);
            if (profesional == null)
            {
                return NotFound();
            }

            return View(profesional);
        }

        [AcceptVerbs("POST")]
        public async Task<IActionResult> AddActivity ([Bind("Id,ProfesionalId,ActividadId,PrecioHora")] ProfesionalActividad profesionalActividad) {

            if (ModelState.IsValid) {
                return await new ProfesionalesActividadesController(_context).Create(profesionalActividad, RedirectToAction(nameof(Details), new { Id = profesionalActividad.ProfesionalId }));
                //return RedirectToAction("Create", "ProfesionalesActividades", new { profesionalActividad = profesionalActividad, redirect = RedirectToAction(nameof(Details), new { Id = profesionalActividad.ProfesionalId }) });
            }

            return RedirectToAction(nameof(Details), new { Id = profesionalActividad.ProfesionalId});
        }

        public async Task<IActionResult> RemoveActivity (int? id) {

            if (id == null) return NotFound();


            int idProfesional = _context.ProfesionalesAvtividades.Include(x => x.Profesional).FirstOrDefault(x => x.Id == id).Profesional.Id;

            return await new ProfesionalesActividadesController(_context).DeleteConfirmed((int)id, RedirectToAction(nameof(Details), new { Id = idProfesional }));
        }

        // GET: Profesionales/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Profesionales/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,NIF,Telefono,Mail,Activo")] Profesional profesional)
        {
            if (ModelState.IsValid)
            {
                _context.Add(profesional);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(profesional);
        }

        // GET: Profesionales/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Profesionales == null)
            {
                return NotFound();
            }

            var profesional = await _context.Profesionales.FindAsync(id);
            if (profesional == null)
            {
                return NotFound();
            }
            return View(profesional);
        }

        // POST: Profesionales/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,NIF,Telefono,Mail,Activo")] Profesional profesional)
        {
            if (id != profesional.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(profesional);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfesionalExists(profesional.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(profesional);
        }

        // GET: Profesionales/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Profesionales == null)
            {
                return NotFound();
            }

            var profesional = await _context.Profesionales
                .FirstOrDefaultAsync(m => m.Id == id);
            if (profesional == null)
            {
                return NotFound();
            }

            return View(profesional);
        }

        // POST: Profesionales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Profesionales == null)
            {
                return Problem("Entity set 'Context.Profesionales'  is null.");
            }
            var profesional = await _context.Profesionales.FindAsync(id);
            if (profesional != null)
            {
                _context.Profesionales.Remove(profesional);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProfesionalExists(int id)
        {
          return (_context.Profesionales?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ProfesionalesMVC/Views/Profesionales/Create.cshtml
@model ProfesionalesMVC.Models.Profesional

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Profesional</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NIF" class="control-label"></label>
                <input asp-for="NIF" class="form-control" />
                <span asp-validation-for="NIF" class="text-danger"></span>
            </div> 
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Activo" /> @Html.DisplayNameFor(model => model.Activo)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProfesionalesMVC/Views/Profesionales/Delete.cshtml
@model ProfesionalesMVC.Models.Profesional

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Profesional</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NIF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NIF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Activo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProfesionalesMVC/Views/Profesionales/Details.cshtml
@model ProfesionalesMVC.Models.Profesional

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Profesional</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NIF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NIF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Activo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activo)
        </dd>
    </dl>
</div>

<div>
    <hr />
    <h4>Actividades</h4>
    @if((ViewBag.Activities as SelectList).Count() > 0) {
        <div class="container-fluid">
            <form class="d-flex" role="search" asp-controller="Profesionales" asp-action="AddActivity" method="post">
                <input name="ProfesionalId" value="@Model.Id" hidden/>
                 <!--<span asp-validation-for="ProfesionalesActividades[0].PrecioHora" class="text-danger"></span>-->
                <select class="form-select" aria-label=".form-select-lg example" style="width:max-content" name="ActividadId" asp-items="ViewBag.Activities"></select>
                <input type="number" name="PrecioHora" style="width: 50px"/>
                <span>€/h</span>
                <button class="btn btn-outline-success mx-3" type="submit">Añadir actividad</button>
            </form>
        </div>
    }

    <table class="table">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Precio""
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (ProfesionalActividad item in ViewBag.ActivitiesDone) {
        <tr>
            <td>
                <a asp-controller="Actividades" asp-action="Details" asp-route-id="@item.ActividadId">@Html.DisplayFor(modelItem => item.Actividad.Nombre)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecioHora)
                €
            </td>
            <td>
                <a class="btn btn-outline-danger btn-sm" asp-action="RemoveActivity" asp-route-id="@item.Id"><i class="fa-solid fa-trash"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>
<div>
    <a class="btn btn-outline-info btn-sm" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a class="btn btn-outline-secondary btn-sm" asp-action="Index">Volver a la lista</a>
</div>

ProfesionalesMVC/Views/Profesionales/Edit.cshtml
@model ProfesionalesMVC.Models.Profesional

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Profesional</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NIF" class="control-label"></label>
                <input asp-for="NIF" class="form-control" />
                <span asp-validation-for="NIF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Activo" /> @Html.DisplayNameFor(model => model.Activo)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProfesionalesMVC/Views/Profesionales/Index.cshtml
@model IEnumerable<ProfesionalesMVC.Models.Profesional>

@{
    ViewData["Title"] = "Index";
}

<h1>Profesionales</h1>
<div class="container-fluid">
        <a class="btn btn-outline-success" asp-action="Create">Añadir profesional</a>
        <form class="d-flex" role="search" style="width:60%; float: right" asp-action="Index" method="get">
            <select class="form-select" aria-label=".form-select-lg example" style="width:max-content" name="field" asp-items="ViewBag.Fields"></select>
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
            <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NIF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Activo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Nombre)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NIF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Activo)
            </td>
            <td>
                <a class="btn btn-outline-warning btn-sm" asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a class="btn btn-outline-info btn-sm" asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a class="btn btn-outline-danger btn-sm" asp-action="Delete" asp-route-id="@item.Id">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>